format = """
$directory\
${custom.arch}\
$git_branch\
$git_status\
$username${hostname}\
$cmd_duration\
$line_break\
$python\
$character"""

add_newline = true

[directory]
style = "cyan"
truncation_length = 0

[custom.arch]
command = "arch"
when = "true"
format = "[ $output]($style) "
style = "242"

[git_branch]
format = "[ $branch]($style)"
style = "242"

[git_status]
format = "([$all_status](218))([ $ahead_behind](cyan)) "
ahead = "⇡"
behind = "⇣"
diverged = "⇡⇣"
modified = "*"
stashed = "≡"
untracked = "?"
staged = "+"
deleted = "✘"
renamed = "»"
conflicted = "="

[username]
format = "[$user]($style)"
style_user = "242"
style_root = "default"

[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "242"

[cmd_duration]
min_time = 5_000
format = "[$duration]($style) "
style = "yellow"

[python]
detect_extensions = []
detect_files = []
detect_folders = []
format = "[$virtualenv ]($style)"
style = "242"

[character]
success_symbol = "[❯](magenta)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](magenta)"
vimcmd_replace_one_symbol = "[❮](magenta)"
vimcmd_replace_symbol = "[❮](magenta)"
vimcmd_visual_symbol = "[❮](magenta)"
