"dein Scripts-----------------------------
if &compatible
  set nocompatible               " Be iMproved
endif

" plugin dir
let s:dein_dir = expand('~/.vim/bundles')

" dein.vim
let s:dein_repo_dir = s:dein_dir . '/repos/github.com/Shougo/dein.vim'

if &runtimepath !~# '/dein.vim'
	if !isdirectory(s:dein_repo_dir)
		execute '!git clone https://github.com/Shougo/dein.vim' s:dein_repo_dir
	endif
	execute 'set runtimepath^=' . fnamemodify(s:dein_repo_dir, ':p')
endif

" set toml
let s:toml_dir = expand('~/.vim/toml/')
let s:toml = s:toml_dir . 'dein.toml'
let s:toml_lazy = s:toml_dir . 'dein_lazy.toml'

" load plugins
if dein#load_state(s:dein_dir)
	call dein#begin(s:dein_dir)
	
	call dein#load_toml(s:toml)
	call dein#load_toml(s:toml_lazy, {'lazy': 1})

	call dein#end()
	call dein#save_state()
endif

" Required:
filetype plugin indent on
syntax enable

" If you want to install not installed plugins on startup.
if dein#check_install()
  call dein#install()
endif

"End dein Scripts-------------------------

set number
set autoindent
set hlsearch
set incsearch
set laststatus=2
set cursorline
set noswapfile
