snippets:
  - name: git status
    keyword: gs
    snippet: git status --short --branch
  - name: git add
    keyword: ga
    snippet: git add
  - name: git commit
    keyword: gc
    snippet: git commit
  - name: git push
    keyword: gp
    snippet: git push
  - name: git pull
    keyword: gl
    snippet: git pull
  - name: zellij
    keyword: zj
    snippet: zellij
  - name: list
    keyword: ll
    snippet: eza --icons -al --group-directories-first --git
  - name: tree
    keyword: lt
    snippet: eza --tree --level=2 --icons
