#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export GOPATH=$HOME/go

path=(
	/usr/local/{bin,sbin}(N-/)
	/opt/homebrew/bin(N-/)
	/Applications/Visual\ Studio\ Code\ -\ Insiders.app/Contents/Resources/app/bin(N-/)
	$HOME/.anyenv/bin(N-/)
	$GOPATH/bin(N-/)
	$path
)

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
