#
# Defines environment variables.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

export COMPDUMPFILE="${ZDOTDIR:-$HOME}/.zcompdump"
export HOMEBREW_DIR=/opt/homebrew
export DOTFILES_DIR="$HOME/dotfiles"
export BREWFILE_SUFFIX=

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi
